# Two main feature branches are used to host URBANopt developments.
# 1. issue2204_gmt_mbl_master (the starting point from which each feature branch is created):
#    this one needs to be periodically synchronized with the master.
# 2. issue2204_gmt_mbl (the end point for feature branches not ready to be merged into the master yet):
#    this one will be synchronized manually after verifying that the changes work within the GMT.

name: Sync URBANopt branch with master
on:
  schedule: # Every day at 7am UTC
    - cron: '0 7 * * *'
jobs:
  sync-issue2204_gmt_mbl_master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Merge master -> issue2204_gmt_mbl_master
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: master
          target_branch: issue2204_gmt_mbl_master
          github_token: ${{ github.token }}

